# Generated by Django 4.0.1 on 2022-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('sensitive_param', models.CharField(max_length=100)),
                ('col_to_be_predicted', models.CharField(max_length=100)),
                ('get_model', models.BooleanField()),
                ('model_type', models.CharField(max_length=50)),
                ('aequitas_mode', models.CharField(max_length=50)),
                ('threshold', models.IntegerField()),
                ('num_params', models.IntegerField()),
                ('model', models.CharField(max_length=200)),
                ('improved_model', models.CharField(max_length=200)),
                ('retraining_input', models.CharField(max_length=200)),
                ('improvement_graph', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
