# Generated by Django 4.0.1 on 2022-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_dataset_datasetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AequitasJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=100)),
                ('sensitive_param', models.CharField(max_length=100)),
                ('col_to_be_predicted', models.CharField(max_length=100)),
                ('get_model', models.BooleanField()),
                ('model_type', models.CharField(max_length=50)),
                ('aequitas_mode', models.CharField(max_length=50)),
                ('threshold', models.IntegerField()),
                ('result_directory', models.CharField(max_length=100)),
                ('dataset_dir', models.CharField(max_length=200)),
                ('num_params', models.IntegerField()),
                ('sensitive_param_idx', models.IntegerField()),
                ('pkl_dir', models.CharField(max_length=200)),
                ('improved_pkl_dir', models.CharField(max_length=200)),
                ('retraining_inputs', models.CharField(max_length=200)),
                ('improvement_graph', models.CharField(max_length=200)),
                ('perturbation_unit', models.IntegerField()),
                ('sample', models.IntegerField()),
                ('num_trials', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='DatasetModel',
        ),
    ]
