# Generated by Django 4.0.1 on 2022-02-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aequitasjob_delete_datasetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aequitasjob',
            name='global_iteration_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aequitasjob',
            name='local_iteration_limit',
            field=models.IntegerField(null=True),
        ),
    ]
