# Generated by Django 4.0.1 on 2022-02-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_aequitasjob_dataset_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aequitasjob',
            name='aequitas_mode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='col_to_be_predicted',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='get_model',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='model_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='num_trials',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='perturbation_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='sample',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='sensitive_param',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aequitasjob',
            name='threshold',
            field=models.IntegerField(null=True),
        ),
    ]
