# Generated by Django 4.0.1 on 2022-02-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_aequitasjob_aequitas_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aequitasjob',
            name='fairness_estimation',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
