export const RUN_AEQUITAS_REQUEST = 'RUN_AEQUITAS_REQUEST';
export const RUN_AEQUITAS_SUCCESS = 'RUN_AEQUITAS_SUCCESS';
export const RUN_AEQUITAS_FAIL = 'RUN_AEQUITAS_FAIL';
export const RUN_AEQUITAS_RESET = 'RUN_AEQUITAS_RESET';

export const GET_AEQUITAS_RESULT_REQUEST = 'GET_AEQUITAS_RESULT_REQUEST';
export const GET_AEQUITAS_RESULT_SUCCESS = 'GET_AEQUITAS_RESULT_SUCCESS';
export const GET_AEQUITAS_RESULT_FAIL = 'GET_AEQUITAS_RESULT_FAIL';

export const DELETE_AEQUITAS_RESULT_REQUEST = 'DELETE_AEQUITAS_RESULT_REQUEST';
export const DELETE_AEQUITAS_RESULT_SUCCESS = 'DELETE_AEQUITAS_RESULT_SUCCESS';
export const DELETE_AEQUITAS_RESULT_FAIL = 'DELETE_AEQUITAS_RESULT_FAIL';
export const DELETE_AEQUITAS_RESULT_RESET = 'DELETE_AEQUITAS_RESULT_RESET';