export const DOWNLOAD_DATASET_REQUEST = 'DOWNLOAD_DATASET_REQUEST';
export const DOWNLOAD_DATASET_SUCCESS = 'DOWNLOAD_DATASET_SUCCESS';
export const DOWNLOAD_DATASET_FAIL = 'DOWNLOAD_DATASET_FAIL';
export const DOWNLOAD_DATASET_RESET = 'DOWNLOAD_DATASET_RESET';

export const DOWNLOAD_MODEL_REQUEST = 'DOWNLOAD_MODEL_REQUEST';
export const DOWNLOAD_MODEL_SUCCESS = 'DOWNLOAD_MODEL_SUCCESS';
export const DOWNLOAD_MODEL_FAIL = 'DOWNLOAD_MODEL_FAIL';
export const DOWNLOAD_MODEL_RESET = 'DOWNLOAD_MODEL_RESET';