export const RUN_AEQUITAS_REQUEST = 'RUN_AEQUITAS_REQUEST';
export const RUN_AEQUITAS_SUCCESS = 'RUN_AEQUITAS_SUCCESS';
export const RUN_AEQUITAS_FAIL = 'RUN_AEQUITAS_FAIL';
export const RUN_AEQUITAS_RESET = 'RUN_AEQUITAS_RESET';