export const SUBMIT_DATASET_REQUEST = 'SUBMIT_DATASET_REQUEST';
export const SUBMIT_DATASET_SUCCESS = 'SUBMIT_DATASET_SUCCESS';
export const SUBMIT_DATASET_FAIL = 'SUBMIT_DATASET_FAIL';

export const CREATE_CONFIG_REQUEST = 'CREATE_CONFIG_REQUEST';
export const CREATE_CONFIG_SUCCESS = 'CREATE_CONFIG_SUCCESS';
export const CREATE_CONFIG_FAIL = 'CREATE_CONFIG_FAIL';

export const UPDATE_CONFIG_REQUEST = 'UPDATE_CONFIG_REQUEST';
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS';
export const UPDATE_CONFIG_FAIL = 'UPDATE_CONFIG_FAIL';